global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'

  routes:
    - match:
        source: loki
      receiver: 'slack-logs'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/XXX/XXX/XXX'
        channel: '#notifications-rdc-prod'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }} ({{ .Alerts.Firing | len }} firing)'
        text: |
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Container:* {{ .Labels.name }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          --------------------------------
          {{ end }}

  - name: 'slack-logs'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/XXX/XXX/XXX'
        channel: '#notifications-rdc-prod'
        send_resolved: false
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }} ({{ .Alerts.Firing | len }} firing)'
        text: |
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.summary }}
          *Severity:* {{ .Labels.severity }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          *Log Message:* {{ .Labels.message }}
          *Container:* {{ .Labels.container }}
          --------------------------------
          {{ end }}