services:

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    restart: always

  prometheus:
    image: prom/prometheus:v3.9.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.template.yml:/etc/prometheus/prometheus.template.yml:ro
      - ./prometheus/entrypoint.sh:/entrypoint.sh:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - prometheus_data:/prometheus
    depends_on:
      - node-exporter
    env_file:
      - ./.env
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  prometheus-meta:
    image: prom/prometheus:v3.9.0
    container_name: prometheus-meta
    volumes:
      - ./prometheus/prometheus-meta.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules_meta/meta_rules.yml:/etc/prometheus/rules/meta_rules.yml:ro
      - prometheus_meta_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=3d'
      - '--storage.tsdb.wal-compression'
      - '--web.enable-lifecycle'
    ports:
      - "9091:9090"
    networks:
      - monitoring
    restart: always

  loki:
    image: grafana/loki:3.6.3
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - ./loki/rules:/loki/rules:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - monitoring
    restart: always

  blackbox:
    image: prom/blackbox-exporter:v0.28.0
    container_name: blackbox
    command: --config.file=/config/blackbox.yml
    volumes:
      - ./blackbox/blackbox.yml:/config/blackbox.yml
    ports:
      - "9115:9115"
    networks:
      - monitoring
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.30.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.template.yml:/etc/alertmanager/alertmanager.template.yml
      - ./alertmanager/entrypoint.sh:/entrypoint.sh:ro
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SLACK_WEBHOOK_CHANNEL_NAME=${SLACK_WEBHOOK_CHANNEL_NAME}
    entrypoint: [ "/bin/sh", "/entrypoint.sh" ]
    ports:
      - "9093:9093"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always

volumes:
  prometheus_data:
  prometheus_meta_data:
  grafana_data:
  loki_data:

networks:
  monitoring:
    driver: bridge