global:
  scrape_interval: 60s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules/meta_rules.yml"

scrape_configs:
  - job_name: 'prometheus-monitoring'
    static_configs:
      - targets: ['prometheus:9090']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

  - job_name: 'loki-monitoring'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'alertmanager-monitoring'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']