global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'aws-production'
    static_configs:
      - targets: ['${PROD_IP}:9100']
        labels:
          env: 'production'

  - job_name: 'aws-production-cadvisor'
    static_configs:
      - targets: ['${PROD_IP}:9180']
        labels:
          env: 'production-cadvisor'

  - job_name: 'aws-uat'
    static_configs:
      - targets: ['${UAT_IP}:9100']
        labels:
          env: 'uat'

  - job_name: 'aws-uat-cadvisor'
    static_configs:
      - targets: ['${UAT_IP}:9180']
        labels:
          env: 'uat-cadvisor'

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [ http_2xx_ignore_ssl ]
    static_configs:
      - targets:
          - "https://${PROD_NLB_URL}/auth"
          - "https://${PROD_NLB_URL}/notification"
          - "https://${PROD_NLB_URL}/referencedata"
          - "https://${PROD_NLB_URL}/report"
          - "https://${PROD_NLB_URL}/stockmanagement"
          - "https://${PROD_NLB_URL}/fulfillment"
          - "https://${PROD_NLB_URL}/requisition"
          - "https://${PROD_NLB_URL}/hapifhir"
          - "https://${PROD_NLB_URL}/cce"
          - "https://${PROD_REPORTING_URL}/"
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115