global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'aws-production'
    static_configs:
      - targets: ['52.58.91.18:9100']
        labels:
          env: 'production'

  - job_name: 'aws-production-cadvisor'
    static_configs:
      - targets: ['52.58.91.18:9180']
        labels:
          env: 'production-cadvisor'

  - job_name: 'aws-uat'
    static_configs:
      - targets: ['${UAT_IP}:9100']
        labels:
          env: 'uat'

  - job_name: 'aws-uat-cadvisor'
    static_configs:
      - targets: ['${UAT_IP}:9180']
        labels:
          env: 'uat-cadvisor'

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [ http_2xx_ignore_ssl ]
    static_configs:
      - targets:
          - "https://52.58.91.18/auth"
          - "https://52.58.91.18/notification"
          - "https://52.58.91.18/referencedata"
          - "https://52.58.91.18/redis"
          - "https://52.58.91.18/report"
          - "https://52.58.91.18/stockmanagement"
          - "https://52.58.91.18/fulfillment"
          - "https://52.58.91.18/requisition"
          - "https://52.58.91.18/consul"
          - "https://52.58.91.18/log"
          - "https://52.58.91.18/nginx"
          - "https://52.58.91.18/hapifhir"
          - "https://52.58.91.18/cce"
          - "https://52.29.12.75/"
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115