global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'aws-production'
    static_configs:
      - targets: ['${PROD_IP}:9100']
        labels:
          env: 'production'

  - job_name: 'aws-production-cadvisor'
    static_configs:
      - targets: ['${PROD_IP}:9180']
        labels:
          env: 'production-cadvisor'

  - job_name: 'aws-uat'
    static_configs:
      - targets: ['${UAT_IP}:9100']
        labels:
          env: 'uat'

  - job_name: 'aws-uat-cadvisor'
    static_configs:
      - targets: ['${UAT_IP}:9180']
        labels:
          env: 'uat-cadvisor'