global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'aws-production'
    static_configs:
      - targets: ['${PROD_IP}:9100']
        labels:
          env: 'production'

  - job_name: 'aws-production-cadvisor'
    static_configs:
      - targets: ['${PROD_IP}:9180']
        labels:
          env: 'production-cadvisor'

  - job_name: 'aws-uat'
    static_configs:
      - targets: ['${UAT_IP}:9100']
        labels:
          env: 'uat'

  - job_name: 'aws-uat-cadvisor'
    static_configs:
      - targets: ['${UAT_IP}:9180']
        labels:
          env: 'uat-cadvisor'

  - job_name: 'blackbox-http-prod'
    metrics_path: /probe
    params:
      module: [ http_2xx_ignore_ssl ]
    static_configs:
      - targets:
          - "https://${PROD_URL}/"
          - "https://${PROD_REPORTING_URL}/"
          - "https://${PROD_NLB_URL}/auth"
          - "https://${PROD_NLB_URL}/notification"
          - "https://${PROD_NLB_URL}/referencedata"
          - "https://${PROD_NLB_URL}/report"
          - "https://${PROD_NLB_URL}/stockmanagement"
          - "https://${PROD_NLB_URL}/fulfillment"
          - "https://${PROD_NLB_URL}/requisition"
          - "https://${PROD_NLB_URL}/hapifhir"
          - "https://${PROD_NLB_URL}/cce"
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

      - source_labels: [ job ]
        regex: blackbox-http-(.*)
        replacement: $1
        target_label: env
      - source_labels: [ __param_target ]
        regex: https?://.*/([^/]+)/?
        replacement: $1
        target_label: service_name
      - source_labels: [ service_name, __param_target ]
        regex: ;https?://([^/.]+)[^/]*.*
        replacement: $1
        target_label: service_name

  - job_name: 'blackbox-http-uat'
    metrics_path: /probe
    params:
      module: [ http_2xx_ignore_ssl ]
    static_configs:
      - targets:
          - "https://${UAT_URL}/"
          - "https://${UAT_REPORTING_URL}/"
          - "https://${UAT_NLB_URL}/auth"
          - "https://${UAT_NLB_URL}/notification"
          - "https://${UAT_NLB_URL}/referencedata"
          - "https://${UAT_NLB_URL}/report"
          - "https://${UAT_NLB_URL}/stockmanagement"
          - "https://${UAT_NLB_URL}/fulfillment"
          - "https://${UAT_NLB_URL}/requisition"
          - "https://${UAT_NLB_URL}/hapifhir"
          - "https://${UAT_NLB_URL}/cce"
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

      - source_labels: [ job ]
        regex: blackbox-http-(.*)
        replacement: $1
        target_label: env
      - source_labels: [ __param_target ]
        regex: https?://.*/([^/]+)/?
        replacement: $1
        target_label: service_name
      - source_labels: [ service_name, __param_target ]
        regex: ;https?://([^/]+).*
        replacement: $1
        target_label: service_name